- alias: Set theme at startup
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: Dark - Cyan
  id: f406963bd1494070ae2daf0695d79b53
- id: kitchen_light_sync_on
  alias: Kitchen Light and Cupboard Sync - On
  trigger:
    platform: state
    entity_id: light.shelly_shdm_1_f3e93b
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.kitchen_cupboard_light
- id: kitchen_light_sync_off
  alias: Kitchen Light and Cupboard Sync - Off
  trigger:
    platform: state
    entity_id: light.shelly_shdm_1_f3e93b
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.kitchen_cupboard_light
- id: '1586510867957'
  alias: Turn Downstairs Bathroom Light off
  description: ''
  trigger:
  - device_id: f110939f4a4a493fa9b6e7c279df15ab
    domain: light
    entity_id: light.shelly_shsw_1_ba680b
    for:
      hours: 0
      minutes: 10
      seconds: 0
    platform: device
    type: turned_on
  condition: []
  action:
  - device_id: f110939f4a4a493fa9b6e7c279df15ab
    domain: light
    entity_id: light.shelly_shsw_1_ba680b
    type: turn_off
  - data:
      data:
        type: announce
      message: You left the light on you rascal
    service: notify.alexa_media_mark_s_echo_dot
- id: '1588281655776'
  alias: Stairs light - Sunset - on
  description: Turn light strip on an hour after sunset
  trigger:
  - event: sunset
    offset: '60'
    platform: sun
  condition: []
  action:
  - data:
      brightness: 6
      effect: solid
      rgb_color:
      - 114
      - 158
      - 255
    entity_id: light.wled_light
    service: light.turn_on
- id: '1589143977791'
  alias: Stairs light - Sunset - off
  description: Turn LED strip off after 10.30pm
  trigger:
  - at: '22:30'
    platform: time
  condition: []
  action:
  - device_id: 28a5ea5a33c541edbbd4131bfcae0929
    domain: light
    entity_id: light.wled_light
    type: turn_off
- id: '1589384931456'
  alias: Stairs - Nightlight - On
  description: ''
  trigger:
  - entity_id: binary_sensor.z1_motion_landing_ias_zone
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.z2_motion_hall_ias_zone
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: or
    conditions:
    - after: '22:30'
      condition: time
    - before: sunrise
      condition: sun
  - condition: state
    entity_id: light.wled_light
    state: 'off'
  action:
  - entity_id: light.wled_light
    service: light.turn_on
  mode: single
- id: '1589390232047'
  alias: Stairs - Nightlight - Off
  description: ''
  trigger:
  - entity_id: binary_sensor.z1_motion_landing_ias_zone
    for: 00:10:00
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.z2_motion_hall_ias_zone
    for: 00:10:00
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: or
    conditions:
    - after: '22:30'
      condition: time
    - before: sunrise
      before_offset: 00:10:00
      condition: sun
  action:
  - device_id: 28a5ea5a33c541edbbd4131bfcae0929
    domain: light
    entity_id: light.wled_light
    type: turn_off
  mode: restart
- id: '1598365780441'
  alias: Baby Monitor - Turn On
  description: ''
  trigger:
  - entity_id: input_boolean.baby_monitor_dad
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: input_boolean.baby_monitor_mum
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: input_boolean.baby_monitor_tablet
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: binary_sensor.nursery_noise
    state: unavailable
  action:
  - data: {}
    service: ffmpeg.start
  mode: single
- id: '1598366206303'
  alias: Baby Monitor - Turn Off
  description: ''
  trigger:
  - entity_id: input_boolean.baby_monitor_dad
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: input_boolean.baby_monitor_mum
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: input_boolean.baby_monitor_tablet
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: not
      conditions:
      - condition: state
        entity_id: binary_sensor.nursery_noise
        state: unavailable
    - condition: state
      entity_id: input_boolean.baby_monitor_dad
      state: 'off'
    - condition: state
      entity_id: input_boolean.baby_monitor_mum
      state: 'off'
    - condition: state
      entity_id: input_boolean.baby_monitor_tablet
      state: 'off'
  action:
  - data: {}
    service: ffmpeg.stop
  mode: single
- id: '1598907036890'
  alias: Baby Monitor - Notify Dad
  description: ''
  trigger:
  - entity_id: binary_sensor.nursery_noise
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.baby_monitor_dad
    state: 'on'
  action:
  - data:
      data:
        attachment:
          content-type: jpg
          hide-thumbnail: false
          url: http://192.168.1.6:8123/local/snapshot.jpg
        entity_id: camera.nursery
        push:
          category: camera
      message: The baby is making noise!
    service: notify.mobile_app_mark_s_iphone
  mode: single
- id: '1600765627311'
  alias: Dishwasher - Warning
  description: ''
  trigger:
  - entity_id: switch.shelly_shsw_pm_f2760d
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      message: Dishwasher has turned off
    service: notify.mobile_app_mark_s_iphone
  mode: single
- id: '1601123895499'
  alias: Dishwasher - Running
  description: ''
  trigger:
  - above: '2000'
    entity_id: sensor.shelly_shsw_pm_f2760d_current_consumption
    for: 00:00:30
    platform: numeric_state
  condition: []
  action:
  - data:
      option: Running
    entity_id: input_select.dishwasher_status
    service: input_select.select_option
  mode: single
- id: '1601124832415'
  alias: Dishwasher - Complete
  description: ''
  trigger:
  - below: '10'
    entity_id: sensor.shelly_shsw_pm_f2760d_current_consumption
    for: 00:06:00
    platform: numeric_state
  condition:
  - condition: state
    entity_id: input_select.dishwasher_status
    state: Running
  action:
  - data:
      option: Complete
    entity_id: input_select.dishwasher_status
    service: input_select.select_option
  - data:
      message: Dishwasher is complete
    service: notify.mobile_app_mark_s_iphone
  - delay: 02:00:00
  - condition: state
    entity_id: input_select.dishwasher_status
    state: Complete
  - data:
      option: Inactive
    entity_id: input_select.dishwasher_status
    service: input_select.select_option
  mode: single
