homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /config


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
# Discover some devices automatically
discovery:

#Speed Test
speedtestdotnet:

# Text to speech
# tts:
#   - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switch.yaml
light: !include light.yaml
sensor: !include sensor.yaml

# person:
#   - name: Mark
#     id: mark6789
#   - name: Katie
#     id: mark6789

hacs:
  token: !secret hacs_token

frontend:
  themes: !include_dir_merge_named ./themes
    # - !include themes.yaml
  javascript_version: auto

# Lovelace
lovelace:
  mode: yaml

# lovelace_gen:

# PLATFORMS
mqtt:
  broker: "mqtt"
  username: !secret mqtt_username
  password: !secret mqtt_password

# # INFLUXDB
# influxdb:
#   host: influxdb
#   port: 8086
#   database: homeassistant
#   username: !secret hass_username
#   password: !secret hass_password
#   default_measurement: state
#   include:
#     domains:
#       - sensor
#       - binary_sensor
#       - switch
#       - light
#   exclude:
#     entities:
#       - sensor.last_boot
#       - sensor.latest_ha_version
#       - sensor.current_ha_version
#       - sensor.yr_symbol
#   tags:
#     instance: prod
#     source: hass
#   # ssl: true
#   # verify_ssl: true
#   # max_retries: 3
#   # default_measurement: state
#   # exclude:
#   #   entities:
#   #      - entity.id1
#   #      - entity.id2
#   #   domains:
#   #      - automation
#   # include:
#   #   entities:
#   #      - entity.id3
#   #      - entity.id4

# UI PANELS
panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:view-dashboard
    url: !env_var graf_env_domain
  portainer:
    title: Portainer
    icon: mdi:dns
    url: !env_var portainer_env_domain
  nodered:
    title: Node Red
    icon: mdi:swap-vertical-variant
    url: !env_var nodered_env_domain
  esphome:
    title: ESPHome
    icon: mdi:chip
    url: !env_var esphome_env_domain
  configurator:
    title: HASS Configurator
    icon: mdi:wrench
    url: !env_var configurator_env_domain

# shopping_list:

ios:

notify:

system_health:

breaking_changes:

browser_mod:
  devices:
    e3c5cf9d-8b56827e:
      name: Kitchen Browser

# weather:

# alarm_control_panel:
#   - platform: yale_smart_alarm
#     username: !secret yale_username
#     password: !secret yale_password

################################################################################################
# RECORDER, HISTORY, LOGGER, INFLUXDB
################################################################################################

logger:
  default: warn
#  logs:
#    pyShelly: debug

## HISTORY
history:

## Recorder
recorder:
  purge_keep_days: 14
  # include:
  #   domains:
  #     sensor
  #     binary_sensor
  #     switch
  #     light
  exclude:
    entities:
      - sensor.latest_ha_version
      - sensor.current_ha_version
      - sensor.ha_version
      - sensor.yr_symbol
      - automation.set_theme_at_startup
      - sensor.last_boot
      - binary_sensor.updater
      - sensor.potential_breaking_changes
      - sensor.next_train_to_wat

###### DARK SKY
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_daily_max_precip_intensity_0d
      - sensor.dark_sky_daily_max_precip_intensity_1d
      - sensor.dark_sky_daily_max_precip_intensity_2d
      - sensor.dark_sky_daily_max_precip_intensity_3d
      - sensor.dark_sky_daily_max_precip_intensity_4d
      - sensor.dark_sky_daily_max_precip_intensity_5d
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_daytime_high_apparent_temperature_0d
      - sensor.dark_sky_daytime_high_apparent_temperature_1d
      - sensor.dark_sky_daytime_high_apparent_temperature_2d
      - sensor.dark_sky_daytime_high_apparent_temperature_3d
      - sensor.dark_sky_daytime_high_apparent_temperature_4d
      - sensor.dark_sky_daytime_high_apparent_temperature_5d
      - sensor.dark_sky_daytime_high_temperature_0d
      - sensor.dark_sky_daytime_high_temperature_1d
      - sensor.dark_sky_daytime_high_temperature_2d
      - sensor.dark_sky_daytime_high_temperature_3d
      - sensor.dark_sky_daytime_high_temperature_4d
      - sensor.dark_sky_daytime_high_temperature_5d
      # - sensor.dark_sky_humidity
      - sensor.dark_sky_humidity_0d
      - sensor.dark_sky_humidity_1d
      - sensor.dark_sky_humidity_2d
      - sensor.dark_sky_humidity_3d
      - sensor.dark_sky_humidity_4d
      - sensor.dark_sky_humidity_5d
      - sensor.dark_sky_icon
      - sensor.dark_sky_icon_0d
      - sensor.dark_sky_icon_1d
      - sensor.dark_sky_icon_2d
      - sensor.dark_sky_icon_3d
      - sensor.dark_sky_icon_4d
      - sensor.dark_sky_icon_5d
      - sensor.dark_sky_nearest_storm_bearing
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_overnight_low_apparent_temperature_0d
      - sensor.dark_sky_overnight_low_apparent_temperature_1d
      - sensor.dark_sky_overnight_low_apparent_temperature_2d
      - sensor.dark_sky_overnight_low_apparent_temperature_3d
      - sensor.dark_sky_overnight_low_apparent_temperature_4d
      - sensor.dark_sky_overnight_low_apparent_temperature_5d
      - sensor.dark_sky_overnight_low_temperature_0d
      - sensor.dark_sky_overnight_low_temperature_1d
      - sensor.dark_sky_overnight_low_temperature_2d
      - sensor.dark_sky_overnight_low_temperature_3d
      - sensor.dark_sky_overnight_low_temperature_4d
      - sensor.dark_sky_overnight_low_temperature_5d
      - sensor.dark_sky_precip
      - sensor.dark_sky_precip_0d
      - sensor.dark_sky_precip_1d
      - sensor.dark_sky_precip_2d
      - sensor.dark_sky_precip_3d
      - sensor.dark_sky_precip_4d
      - sensor.dark_sky_precip_5d
      - sensor.dark_sky_precip_accumulation_0d
      - sensor.dark_sky_precip_accumulation_1d
      - sensor.dark_sky_precip_accumulation_2d
      - sensor.dark_sky_precip_accumulation_3d
      - sensor.dark_sky_precip_accumulation_4d
      - sensor.dark_sky_precip_accumulation_5d
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_intensity_0d
      - sensor.dark_sky_precip_intensity_1d
      - sensor.dark_sky_precip_intensity_2d
      - sensor.dark_sky_precip_intensity_3d
      - sensor.dark_sky_precip_intensity_4d
      - sensor.dark_sky_precip_intensity_5d
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_precip_probability_0d
      - sensor.dark_sky_precip_probability_1d
      - sensor.dark_sky_precip_probability_2d
      - sensor.dark_sky_precip_probability_3d
      - sensor.dark_sky_precip_probability_4d
      - sensor.dark_sky_precip_probability_5d
      - sensor.dark_sky_pressure
      - sensor.dark_sky_pressure_0d
      - sensor.dark_sky_pressure_1d
      - sensor.dark_sky_pressure_2d
      - sensor.dark_sky_pressure_3d
      - sensor.dark_sky_pressure_4d
      - sensor.dark_sky_pressure_5d
      - sensor.dark_sky_summary
      - sensor.dark_sky_summary_0d
      - sensor.dark_sky_summary_1d
      - sensor.dark_sky_summary_2d
      - sensor.dark_sky_summary_3d
      - sensor.dark_sky_summary_4d
      - sensor.dark_sky_summary_5d
      #sensor.dark_sky_temperature
      - sensor.dark_sky_uv_index
      - sensor.dark_sky_uv_index_0d
      - sensor.dark_sky_uv_index_1d
      - sensor.dark_sky_uv_index_2d
      - sensor.dark_sky_uv_index_3d
      - sensor.dark_sky_uv_index_4d
      - sensor.dark_sky_uv_index_5d
      - sensor.dark_sky_visibility
      - sensor.dark_sky_visibility_0d
      - sensor.dark_sky_visibility_1d
      - sensor.dark_sky_visibility_2d
      - sensor.dark_sky_visibility_3d
      - sensor.dark_sky_visibility_4d
      - sensor.dark_sky_visibility_5d
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_bearing_0d
      - sensor.dark_sky_wind_bearing_1d
      - sensor.dark_sky_wind_bearing_2d
      - sensor.dark_sky_wind_bearing_3d
      - sensor.dark_sky_wind_bearing_4d
      - sensor.dark_sky_wind_bearing_5d
      - sensor.dark_sky_wind_speed
      - sensor.dark_sky_wind_speed_0d
      - sensor.dark_sky_wind_speed_1d
      - sensor.dark_sky_wind_speed_2d
      - sensor.dark_sky_wind_speed_3d
      - sensor.dark_sky_wind_speed_4d
      - sensor.dark_sky_wind_speed_5d
      - sun.sun
