homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_lat
  longitude: !secret home_long
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages


# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
# Discover some devices automatically
discovery:

#Speed Test
speedtestdotnet:

# Text to speech
# tts:
#   - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
switch: !include switch.yaml
light: !include light.yaml
sensor: !include sensor.yaml

logger:
  default: warn

hacs:
  token: !secret hacs_token

frontend:
  themes: !include themes.yaml
  javascript_version: auto

# Lovelace
lovelace:
  mode: yaml

# PLATFORMS
mqtt:
  broker: "mqtt"
  username: !secret mqtt_username
  password: !secret mqtt_password

# INFLUXDB
influxdb:
  host: influxdb
  port: 8086
  database: homeassistant
  username: !secret hass_username
  password: !secret hass_password
  default_measurement: state
  include:
    domains:
      - sensor
      - binary_sensor
      - switch
      - light
  exclude:
    entities:
      - sensor.last_boot
      - sensor.latest_ha_version
      - sensor.current_ha_version
      - sensor.yr_symbol
  tags:
    instance: prod
    source: hass
  # ssl: true
  # verify_ssl: true
  # max_retries: 3
  # default_measurement: state
  # exclude:
  #   entities:
  #      - entity.id1
  #      - entity.id2
  #   domains:
  #      - automation
  # include:
  #   entities:
  #      - entity.id3
  #      - entity.id4

## Recorder
recorder:
  purge_keep_days: 31
  include:
    domains:
      sensor
  # exclude:
  #   entities:
  #     - sensor.dark_sky_*

# UI PANELS
panel_iframe:
  grafana:
    title: Grafana
    icon: mdi:view-dashboard
    url: !env_var graf_env_domain
  configurator:
    title: HASS Configurator
    icon: mdi:wrench
    url: http://localhost:3218
  portainer:
    title: Portainer
    icon: mdi:dns
    url: !env_var portainer_env_domain
  # node_red:
  #   title: Node Red
  #   icon: mdi:swap-vertical-variant
  #   url: !env_var nodered_env_domain

shopping_list:

system_health:

breaking_changes:

# weather:

speedtestdotnet:
  scan_interval:
    minutes: 20
  server_id: 2789  # Vodafone UK
  monitored_conditions:
    - ping
    - download
    - upload

# Example configuration.yaml entry with manually specified addresses
sonos:
  media_player:
    hosts: 192.168.1.11

alarm_control_panel:
  - platform: yale_smart_alarm
    username: !secret yale_username
    password: !secret yale_password
