#################################################################
##  Switches
#################################################################

  - platform: mqtt
    name: "living_room_ceiling"
    state_topic: "test.home/living-room/lights/ceiling/state"
    command_topic: "test.home/living-room/lights/ceiling/set"
    availability_topic: "test.home/living-room/lights/ceiling/available"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
    unique_id: 00112233445566
