title: Home Dashboard

resources:
  # - url: /hacsfiles/compact-custom-header/compact-custom-header.js
  #   type: module
  - url: /hacsfiles/custom-header/custom-header.js
    type: module
  - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
    type: module
  # - url: /hacsfiles/lovelace-layout-card/layout-card.js
  #   type: module
  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: js
  - url: /hacsfiles/bar-card/bar-card.js
    type: js
  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /hacsfiles/lovelace-dummy-entity-row/dummy-entity-row.js
    type: module
  - url: /hacsfiles/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /local/custom_ui/dark-sky-weather-card.js?v=7.1
    type: module
  - url: /local/floorplan/floorplan-card.js
    type: module
  - url: /hacsfiles/button-card/button-card.js
    type: module
  - url: /hacsfiles/flex-table-card/flex-table-card.js
    type: js
  - url: /hacsfiles/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: js
  - url: /local/custom_ui/thermostat-card.js
    type: module
  - url: /hacsfiles/lovelace-card-mod/card-mod.js
    type: module
  - type: css
    url: /local/custom_lovelace/custom.css
  - url: /hacsfiles/config-template-card/config-template-card.js
    type: module
  - url: /local/custom_ui/agile-rates-card.js
    type: module

custom_header:
  compact_mode: true
  options: clock
  swipe: true
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
  # kiosk_mode: true
  # conditional_styles:
  #   - user_agent: Mobile
  #     # condition:
  #     #   state: off                      # When input_boolean is off...
  #     # background: url('/local/bg.jpg')  # change background image and...
  #     config:
  #       options: show
  #       hide_tabs: 1
  # menu: overflow
  hide_tabs: '1, 2, 3'
  exceptions:
    - conditions:
        user_agent: iPhone
        media_query: "(max-width: 500px)"
      config:
        options: show
        hide_tabs: home
        default_tab: overview-buttons

views: !include_dir_merge_list www/views

#   - title: Overview
#     panel: true
#     id: overview
#     path: home
#     icon: mdi:home-outline
# #    themes: !include themes.yaml
# #    theme: dark_orange
#
#     type: module
#     cards:
#     - type: vertical-stack
#       cards:
#       - type: markdown
#         title: Lovelace
#         content: >
#           Welcome to your **Lovelace UI**.
#
#       - type: glance
#         title: Lights
#         show_name: true
#         show_state: true
#         entities:
#           - switch.living_room_ceiling
#           - light.dining_room_ceiling
#
#       - type: shopping-list
#
#       #Needed for compact header. Every view. Main config in first view.
#       - type: custom:compact-custom-header
#         main_config: true
#
#     # Title of the view. Will be used as the tooltip for tab icon
#   - title: Second view
#     panel: true
#     icon: mdi:av-timer
#     id: second-view
#     path: second-view
#     cards:
#     - type: vertical-stack
#       cards:
#       # The markdown card will render markdown text.
#       - type: markdown
#         title: Lovelace
#         content: >
#           Welcome to your **Lovelace UI**.
#
#       #Needed for compact header. Every view. Main config in first view.
#       - type: custom:compact-custom-header
