  - title: Overview
    id: overview
    path: home
    icon: mdi:home-assistant
    type: module
    panel: true
    cards:
    - type: custom:layout-card
      column_num: 4
      layout: vertical
      # column_width: [1216px, 1216px, 1216px, 1216px]
      max_width: [10%, 30%, 30%, 30%]
      cards:
      - type: "custom:button-card"
        entity: person.mark_colling
        icon: mdi:shoe-print
        color: var(--primary-text-color)
        color_type: icon
        default_color: var(--disabled-text-color)
        action: more_info
        name: Mark
        state:
          - value: 'home'
            icon: mdi:home-account
            color: var(--primary-color)
        # style: |
        #   ha-card {
        #     background:
        #     {% if is_state('person.mark_colling', 'home') %}
        #       var(--primary-color)
        #     {% else %}
        #       var(--disabled-text-color)
        #     {% endif %};
        #   }
        styles:
          card:
          - height: 98px
          # - font-size: 12px
          # - font-weight: bold
      - type: "custom:button-card"
        entity: person.katie
        icon: mdi:shoe-print
        color: var(--primary-text-color)
        color_type: icon
        default_color: var(--disabled-text-color)
        action: more_info
        state:
          - value: 'home'
            icon: mdi:home-account
            color: var(--primary-color)
        name: Katie
        styles:
          card:
          - height: 98px
          # - font-size: 12px
          # - font-weight: bold
      # - type: "custom:button-card"
      #   entity: switch.living_room_ceiling
      #   # icon: mdi:lightbulb
      #   color: auto
      #   color_type: icon
      #   default_color: rgb(255, 233, 155)
      #   action: more_info
      #   name: Living Room Switch
      #   styles:
      #     card:
      #     - height: 98px
      #   state:
      #     - value: default
      #       colour: var(--disabled-text-color)
      #       styles:
      #         label:
      #           - colour: var(--disabled-text-color)
      #     # - font-size: 12px
      #     # - font-weight: bold
      # - type: "custom:button-card"
      #   entity: light.dining_room_ceiling
      #   # icon: mdi:lightbulb
      #   color: auto
      #   color_type: icon
      #   default_color: rgb(255, 233, 155)
      #   action: more_info
      #   name: Dining Room Light
      #   styles:
      #     card:
      #     - height: 98px
      #     # - font-size: 12px
      #     # - font-weight: bold
      # - type: "custom:button-card"
      #   entity: switch.test_room_light
      #   # icon: mdi:lightbulb
      #   color: auto
      #   color_type: icon
      #   default_color: rgb(255, 233, 155)
      #   action: more_info
      #   name: Test Light
      #   styles:
      #     card:
      #     - height: 98px
      #     # - font-size: 12px
      #     # - font-weight: bold
      # - type: "custom:button-card"
      #   entity: binary_sensor.test_room_opening
      #   # icon: mdi:lightbulb
      #   color: auto
      #   color_type: icon
      #   default_color: rgb(255, 233, 155)
      #   action: more_info
      #   name: Test Opening
      #   styles:
      #     card:
      #     - height: 98px
          # - font-size: 12px
          # - font-weight: bold
      # - type: "custom:button-card"
      #   entity: light.dining_room_ceiling
      #   # icon: mdi:lightbulb
      #   color: auto
      #   color_type: icon
      #   default_color: rgb(255, 233, 155)
      #   action: more_info
      #   name: Button 6
      #   styles:
      #     card:
      #     - height: 98px
      #     # - font-size: 12px
      #     # - font-weight: bold
      # - type: "custom:button-card"
      #   entity: light.dining_room_ceiling
      #   # icon: mdi:lightbulb
      #   color: auto
      #   color_type: icon
      #   default_color: rgb(255, 233, 155)
      #   action: more_info
      #   name: Button 7
      #   styles:
      #     card:
      #     - height: 98px
      #     # - font-size: 12px
      #     # - font-weight: bold
      - break
      - !include ../components/A_ground_floorplan.yaml

      # - type: 'custom:floorplan-card'
      #   # title: Simple Floorplan
      #   config:
      #     image: /local/floorplan/ground-floorplan.svg
      #     rules:
      #       - entities:
      #           - binary_sensor.living_room_motion_fill
      #           - binary_sensor.library_motion_fill
      #           - binary_sensor.hallway_motion_fill
      #           - binary_sensor.kitchen_motion_fill
      #           - binary_sensor.front_door_motion_fill
      #           - binary_sensor.downstairs_bathroom_motion_fill
      #           - binary_sensor.outdoor_side_motion_fill
      #           - binary_sensor.outdoor_front_motion_fill
      #           - binary_sensor.outdoor_back_motion_fill
      #         states:
      #           - class: 'motion-fill-inactive'
      #             state: 'off'
      #           - class: 'motion-fill-active'
      #             state: 'on'
      #
      #       - entities:
      #           - binary_sensor.living_room_motion_border
      #           - binary_sensor.library_motion_border
      #           - binary_sensor.kitchen_motion_border
      #           - binary_sensor.hallway_motion_border
      #           - binary_sensor.front_door_motion_border
      #           - binary_sensor.downstairs_bathroom_motion_border
      #         states:
      #           - class: 'motion-border-inactive'
      #             state: 'off'
      #           - class: 'motion-border-active'
      #             state: 'on'
      #
      #       - entities:
      #           - binary_sensor.living_room_window_4_battery
      #           - binary_sensor.living_room_window_1_battery
      #           - binary_sensor.living_room_window_2_battery
      #           - binary_sensor.hallway_door_1_battery
      #           - binary_sensor.library_door_1_battery
      #           - binary_sensor.kitchen_window_1_battery
      #           - binary_sensor.kitchen_window_2_battery
      #           - binary_sensor.downstairs_bathroom_window_1_battery
      #           - binary_sensor.kitchen_door_1_battery
      #           - binary_sensor.living_room_window_3_battery
      #         states:
      #           - class: 'battery-warning-off'
      #             state: 'off'
      #           - class: 'battery-warning-on'
      #             state: 'on'
      #
      #       - entities:
      #           - binary_sensor.downstairs_bathroom_window_1
      #         states:
      #           - class: 'opening-closed'
      #             state: 'off'
      #           - class: 'opening-open'
      #             state: 'on'
      #           - class: 'opening-unavailable'
      #             state: 'unavailable'
      #
      #       - entities:
      #           - sensor.living_room_window_2
      #         states:
      #           - class: 'opening-closed'
      #             state: 'off'
      #           - class: 'opening-open'
      #             state: 'on'
      #           - class: 'opening-unavailable'
      #             state: 'unavailable'
      #
      #     # - name: Sensors
      #       - entities:
      #           - sensor.day_room_temperature
      #           - sensor.kitchen_temperature
      #         text_template: '${entity.state ? entity.state + "\u00b0C" : "\#\#"}'
      #         class_template: '${entity.state ? "active" : ""}'
      #           # '
      #           # var temp = parseFloat(entity.state.replace("°", ""));
      #           # if (temp < 10)
      #           #   return "temp-low";
      #           # else if (temp < 30)
      #           #   return "temp-medium";
      #           # else
      #           #   return "temp-high";
      #           # '
      #       - entities:
      #           - sensor.day_room_humidity
      #           - sensor.kitchen_humidity
      #         text_template: '${entity.state ? entity.state + "\%" : "\#\#"}'
      #         class_template: '${entity.state ? "active" : ""}'
      #       # - entities:
      #       #     - switch.living_room_motion
      #       #   states:
      #       #     - class: 'living-room_fill'
      #       #       state: 'off'
      #       #     - class: 'living-room_fill'
      #       #       state: 'on'
      #     stylesheet: /local/floorplan/floorplan.css

      - break
      - !include ../components/B_first_floorplan.yaml
      # - type: 'custom:floorplan-card'
      #   # title: Simple Floorplan
      #   config:
      #     image: /local/floorplan/first-floorplan.svg
      #     rules:
      #       - entities:
      #         - binary_sensor.landing_motion_fill
      #         - binary_sensor.bedroom_3_motion_fill
      #         - binary_sensor.bedroom_1_motion_fill
      #         - binary_sensor.bathroom_motion_fill
      #         - binary_sensor.bedroom_2_motion_fill
      #         states:
      #           - class: 'motion-fill-inactive'
      #             state: 'off'
      #           - class: 'motion-fill-active'
      #             state: 'on'
      #
      #       - entities:
      #         - binary_sensor.landing_motion_border
      #         - binary_sensor.bedroom_3_motion_border
      #         - binary_sensor.bedroom_1_motion_border
      #         - binary_sensor.bathroom_motion_border
      #         - binary_sensor.bedroom_2_motion_border
      #         states:
      #           - class: 'motion-border-inactive'
      #             state: 'off'
      #           - class: 'motion-border-active'
      #             state: 'on'
      #
      #       - entities:
      #         - binary_sensor.bedroom_1_window_1_battery
      #         - binary_sensor.bedroom_1_window_4_battery
      #         - binary_sensor.bedroom_1_window_2_battery
      #         - binary_sensor.bedroom_1_window_3_battery
      #         - binary_sensor.bedroom_2_window_1_battery
      #         - binary_sensor.bathroom_window_1_battery
      #         - binary_sensor.bedroom_3_window_1_battery
      #         - binary_sensor.bedroom_1_window_5_battery
      #         states:
      #           - class: 'battery-warning-off'
      #             state: 'off'
      #           - class: 'battery-warning-on'
      #             state: 'on'
      #
      #     stylesheet: /local/floorplan/floorplan.css
      #
      - type: custom:mini-media-player
        title: Sonos
        entity: media_player.living_room
        hide:
          power: false
          icon: true
          source: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.living_room
              name: Sonos Living Room

      - break

      - type: custom:dark-sky-weather-card
        entity_current_conditions: sensor.dark_sky_icon
        entity_temperature: sensor.dark_sky_temperature
        entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1d
        entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2d
        entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3d
        entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4d
        entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5d
        entity_forecast_icon_1: sensor.dark_sky_icon_1d
        entity_forecast_icon_2: sensor.dark_sky_icon_2d
        entity_forecast_icon_3: sensor.dark_sky_icon_3d
        entity_forecast_icon_4: sensor.dark_sky_icon_4d
        entity_forecast_icon_5: sensor.dark_sky_icon_5d
        entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_0d
        entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1d
        entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2d
        entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3d
        entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4d
        entity_summary_1: sensor.dark_sky_summary_1d
        entity_summary_2: sensor.dark_sky_summary_2d
        entity_summary_3: sensor.dark_sky_summary_3d
        entity_summary_4: sensor.dark_sky_summary_4d
        entity_summary_5: sensor.dark_sky_summary_5d
        entity_sun: sun.sun
        entity_visibility: sensor.dark_sky_visibility
        entity_daytime_high: sensor.dark_sky_daytime_high_temperature_0d
        entity_wind_bearing: sensor.dark_sky_wind_bearing
        entity_wind_speed: sensor.dark_sky_wind_speed
        entity_humidity: sensor.dark_sky_humidity
        entity_pressure: sensor.dark_sky_pressure
        entity_apparent_temp: sensor.dark_sky_apparent_temperature
        entity_daily_summary: sensor.dark_sky_daily_summary
        entity_pop: sensor.dark_sky_precip_probability
        entity_pop_intensity: sensor.dark_sky_precip_intensity
        entity_pop_1: sensor.dark_sky_precip_probability_1d
        entity_pop_2: sensor.dark_sky_precip_probability_2d
        entity_pop_3: sensor.dark_sky_precip_probability_3d
        entity_pop_4: sensor.dark_sky_precip_probability_4d
        entity_pop_5: sensor.dark_sky_precip_probability_5d
        static_icons: true

      - type: custom:flex-table-card
        # title: Trains to Waterloo
        max_rows: 5
        entities:
          include: sensor.next_train_to_wat
        columns:
          # - name: Origin
          #   attr_as_list: next_trains
          #   modify: x.origin_name
          # - name: Destination
          #   attr_as_list: next_trains
          #   modify: x.destination_name
          - name: Next Train to WAT
            attr_as_list: next_trains
            modify: x.scheduled
          - name: Est
            attr_as_list: next_trains
            modify: x.estimated
          - name: Status
            attr_as_list: next_trains
            modify: x.status
        on_empty:
          # to hide the entire flex-table (default: false)
          hide: true
          # if `!hide` show the following text instead of content
          # text: "No trains to show"
          # do not show the column headers (default: false)
          hide_headers: true

      # - type: glance
      #   title: Lights
      #   show_name: true
      #   show_state: true
      #   entities:
      #     - switch.living_room_ceiling
      #     - light.dining_room_ceiling
      #     - switch.test_room_light

      # - type: vertical-stack
      #   cards:
      #   - type: markdown
      #     title: Lovelace
      #     content: >
      #       Welcome to your **Lovelace UI**.
