  - title: Overview
    id: overview
    path: home
    icon: mdi:home-assistant
    type: module
    panel: true
    cards:
    - type: custom:layout-card
      column_num: 4
      layout: vertical
      column_width:
      max_width: [10%, 30%, 30%, 30%]
      cards:
      - type: "custom:button-card"
        entity: switch.living_room_ceiling
        # icon: mdi:lightbulb
        color: auto
        color_type: icon
        default_color: rgb(255, 233, 155)
        action: more_info
        name: Button 1
        styles:
          card:
          - height: 98px
        state:
        - value: 'unavailable'
          styles:
            icon:
              - colour: var(--disabled-text-color)
          # - font-size: 12px
          # - font-weight: bold
      - type: "custom:button-card"
        entity: light.dining_room_ceiling
        # icon: mdi:lightbulb
        color: auto
        color_type: icon
        default_color: rgb(255, 233, 155)
        action: more_info
        name: Button 2
        styles:
          card:
          - height: 98px
          # - font-size: 12px
          # - font-weight: bold
      - type: "custom:button-card"
        entity: light.dining_room_ceiling
        # icon: mdi:lightbulb
        color: auto
        color_type: icon
        default_color: rgb(255, 233, 155)
        action: more_info
        name: Button 3
        styles:
          card:
          - height: 98px
          # - font-size: 12px
          # - font-weight: bold
      - type: "custom:button-card"
        entity: light.dining_room_ceiling
        # icon: mdi:lightbulb
        color: auto
        color_type: icon
        default_color: rgb(255, 233, 155)
        action: more_info
        name: Button 4
        styles:
          card:
          - height: 98px
          # - font-size: 12px
          # - font-weight: bold
      - type: "custom:button-card"
        entity: light.dining_room_ceiling
        # icon: mdi:lightbulb
        color: auto
        color_type: icon
        default_color: rgb(255, 233, 155)
        action: more_info
        name: Button 5
        styles:
          card:
          - height: 98px
          # - font-size: 12px
          # - font-weight: bold
      - type: "custom:button-card"
        entity: light.dining_room_ceiling
        # icon: mdi:lightbulb
        color: auto
        color_type: icon
        default_color: rgb(255, 233, 155)
        action: more_info
        name: Button 6
        styles:
          card:
          - height: 98px
          # - font-size: 12px
          # - font-weight: bold
      - type: "custom:button-card"
        entity: light.dining_room_ceiling
        # icon: mdi:lightbulb
        color: auto
        color_type: icon
        default_color: rgb(255, 233, 155)
        action: more_info
        name: Button 7
        styles:
          card:
          - height: 98px
          # - font-size: 12px
          # - font-weight: bold
      - break

      - type: 'custom:floorplan-card'
        # title: Simple Floorplan
        config:
          image: /local/floorplan/ground-floorplan.svg
          rules:
            - entities:
                - light.dining_room_ceiling
                - sensor.living_room_ceiling
              states:
                - class: 'binary-sensor-off'
                  state: 'off'
                - class: 'binary-sensor-on'
                  state: 'on'
          stylesheet: /local/floorplan/examples/simple/simple.css?v=1.1.14

      - break

      - type: 'custom:floorplan-card'
        # title: Simple Floorplan
        config:
          image: /local/floorplan/first-floorplan.svg
          rules:
            - entities:
                - light.dining_room_ceiling
                - sensor.living_room_ceiling
              states:
                - class: 'binary-sensor-off'
                  state: 'off'
                - class: 'binary-sensor-on'
                  state: 'on'
          stylesheet: /local/floorplan/examples/simple/simple.css?v=1.1.14

      - type: custom:mini-media-player
        title: Sonos
        entity: media_player.living_room
        hide:
          power: false
          icon: true
          source: true
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.living_room
              name: Sonos Living Room

      - break

      - type: custom:dark-sky-weather-card
        entity_current_conditions: sensor.dark_sky_icon
        entity_temperature: sensor.dark_sky_temperature
        entity_forecast_high_temp_1: sensor.dark_sky_daytime_high_temperature_1d
        entity_forecast_high_temp_2: sensor.dark_sky_daytime_high_temperature_2d
        entity_forecast_high_temp_3: sensor.dark_sky_daytime_high_temperature_3d
        entity_forecast_high_temp_4: sensor.dark_sky_daytime_high_temperature_4d
        entity_forecast_high_temp_5: sensor.dark_sky_daytime_high_temperature_5d
        entity_forecast_icon_1: sensor.dark_sky_icon_1d
        entity_forecast_icon_2: sensor.dark_sky_icon_2d
        entity_forecast_icon_3: sensor.dark_sky_icon_3d
        entity_forecast_icon_4: sensor.dark_sky_icon_4d
        entity_forecast_icon_5: sensor.dark_sky_icon_5d
        entity_forecast_low_temp_1: sensor.dark_sky_overnight_low_temperature_0d
        entity_forecast_low_temp_2: sensor.dark_sky_overnight_low_temperature_1d
        entity_forecast_low_temp_3: sensor.dark_sky_overnight_low_temperature_2d
        entity_forecast_low_temp_4: sensor.dark_sky_overnight_low_temperature_3d
        entity_forecast_low_temp_5: sensor.dark_sky_overnight_low_temperature_4d
        entity_summary_1: sensor.dark_sky_summary_1d
        entity_summary_2: sensor.dark_sky_summary_2d
        entity_summary_3: sensor.dark_sky_summary_3d
        entity_summary_4: sensor.dark_sky_summary_4d
        entity_summary_5: sensor.dark_sky_summary_5d
        entity_sun: sun.sun
        entity_visibility: sensor.dark_sky_visibility
        entity_daytime_high: sensor.dark_sky_daytime_high_temperature_0d
        entity_wind_bearing: sensor.dark_sky_wind_bearing
        entity_wind_speed: sensor.dark_sky_wind_speed
        entity_humidity: sensor.dark_sky_humidity
        entity_pressure: sensor.dark_sky_pressure
        entity_apparent_temp: sensor.dark_sky_apparent_temperature
        entity_daily_summary: sensor.dark_sky_daily_summary
        entity_pop: sensor.dark_sky_precip_probability
        entity_pop_intensity: sensor.dark_sky_precip_intensity
        entity_pop_1: sensor.dark_sky_precip_probability_1d
        entity_pop_2: sensor.dark_sky_precip_probability_2d
        entity_pop_3: sensor.dark_sky_precip_probability_3d
        entity_pop_4: sensor.dark_sky_precip_probability_4d
        entity_pop_5: sensor.dark_sky_precip_probability_5d
        static_icons: true

      - type: glance
        title: Lights
        show_name: true
        show_state: true
        entities:
          - switch.living_room_ceiling
          - light.dining_room_ceiling

      # - type: vertical-stack
      #   cards:
      #   - type: markdown
      #     title: Lovelace
      #     content: >
      #       Welcome to your **Lovelace UI**.

      #Needed for compact header. Every view. Main config in first view.
      - type: custom:compact-custom-header
        main_config: true
