    # Title of the view. Will be used as the tooltip for tab icon
  - title: Cameras
    icon: mdi:cctv
    id: cameras
    path: cameras
    cards:
    - type: vertical-stack
      cards:
      # The markdown card will render markdown text.
      - type: markdown
        title: cameras
        content: >
          Welcome to your **Lovelace UI**.
