    # Title of the view. Will be used as the tooltip for tab icon
  - title: First Floor
    icon: mdi:home-outline
    id: first-floor
    path: first-floor
    cards:
    - type: vertical-stack
      cards:
      # The markdown card will render markdown text.
      - type: markdown
        title: First Floor
        content: >
          Welcome to your **Lovelace UI**.

      #Needed for compact header. Every view. Main config in first view.
      - type: custom:compact-custom-header
