# Title of the view. Will be used as the tooltip for tab icon
- title: Heating
  icon: mdi:home-analytics
  id: heating
  path: heating
  panel: true
  cards:
    # - type: horizontal-stack
    #   cards:
    - type: custom:layout-card
      max_width: 600px
      cards:
      - type: vertical-stack
        cards:
        - type: entities
          title: Temperature Sensors
          entities:
          - entity: sensor.xiaomi_1_temperature
          - entity: sensor.xiaomi_2_temperature
        #   - entity: sensor.tesla_outside_temp
          - entity: weather.dark_sky
        - type: entities
          title: Downstairs Heating
          show_header_toggle: false
          entities:
          - entity: sensor.wiser_heating
          - entity: climate.wiser_living_room
          - entity: climate.wiser_kitchen
        - type: entities
          title: Upstairs Heating
          show_header_toggle: false
          entities:
          - entity: climate.wiser_master
          - entity: climate.wiser_bedroom_2
          - entity: climate.wiser_bedroom_3
        # - type: entities
        #   title: Heating Modes
        #   show_header_toggle: false
        #   entities:
        #   - entity: switch.wiser_away_mode
        #   - entity: switch.wiser_comfort_mode
        #   - entity: switch.wiser_eco_mode
        #   - entity: switch.wiser_valve_protection
      - break
      - type: vertical-stack
        cards:
          - type: iframe
            # url: http://grafana.dev.prettyfly.net/d/ZURDkF1Wz/house-temperatures?orgId=1&theme=light&fullscreen
            url: !secret grafana_URL
            aspect_ratio: 110%

    # - type: vertical-stack
    #   cards:
    #   - type: entities
    #     title: Upstairs Lights
    #     show_header_toggle: true
    #     entities:
    #     - type: section
    #       label: Bedrooms
    #     - entity: light.shelly_shdm_1_db3e10
    #       secondary_info: last-changed
    #     - entity: light.shelly_shdm_1_f3a14a
    #       secondary_info: last-changed
    #     - entity: light.shelly_shsw_1_b90033
    #       secondary_info: last-changed
    #     - type: section
    #       label: Landing
    #     - entity: light.shelly_shsw_1_c4e83e
    #       secondary_info: last-changed
    #     - type: section
    #       label: Bathroom
    #     - entity: light.shelly_shsw_1_ba6933
    #       secondary_info: last-changed
