    # Title of the view. Will be used as the tooltip for tab icon
  - title: Weather
    icon: mdi:weather-partly-cloudy
    id: weather
    path: weather
    cards:
    - type: vertical-stack
      cards:
      # The markdown card will render markdown text.
      - type: markdown
        title: Weather
        content: >
          Welcome to your **Lovelace UI**.
