    # Title of the view. Will be used as the tooltip for tab icon
  - title: Cameras
    icon: mdi:cctv
    id: cameras
    path: cameras
    panel: true
    cards:
      - type: custom:layout-card
        max_width: 600px
        cards:
        - type: vertical-stack
          cards:
          # The markdown card will render markdown text.
            - camera_image: camera.prettyflynas_drive_camera
              camera_view: live
              entities: []
              title: Drive Camera
              type: picture-glance
            - camera_image: camera.prettyflynas_back_garden_camera
              camera_view: live
              entities: []
              title: Garden Camera
              type: picture-glance
        - break
        - type: vertical-stack
          cards:
            - camera_image: camera.prettyflynas_porch_camera
              camera_view: live
              entities: []
              title: Porch Camera
              type: picture-glance
            - type: vertical-stack
              cards:
                - camera_image: camera.nursery
                  camera_view: live
                  entities: []
                  title: Nursery Camera
                  type: picture-glance
