    # Title of the view. Will be used as the tooltip for tab icon
  - title: Cameras
    icon: mdi:cctv
    id: cameras
    path: cameras
    cards:
    - type: vertical-stack
      cards:
      # The markdown card will render markdown text.
        - camera_image: camera.drive
          camera_view: live
          entities: []
          title: Drive Camera
          type: picture-glance