
- path: car
  title: Car
  panel: true
  icon: "mdi:car-connected"
  cards:
    - type: iframe
        # url: http://grafana.dev.prettyfly.net/d/ZURDkF1Wz/house-temperatures?orgId=1&theme=light&fullscreen
      url: !secret grafana_URL_tez
      aspect_ratio: 110%

    # - type: vertical-stack
    #   cards:
    #   - type: entities
    #     title: Upstairs Lights
    #     show_header_toggle: true
    #     entities:
    #     - type: section
    #       label: Bedrooms
    #     - entity: light.shelly_shdm_1_db3e10
    #       secondary_info: last-changed
    #     - entity: light.shelly_shdm_1_f3a14a
    #       secondary_info: last-changed
    #     - entity: light.shelly_shsw_1_b90033
    #       secondary_info: last-changed
    #     - type: section
    #       label: Landing
    #     - entity: light.shelly_shsw_1_c4e83e
    #       secondary_info: last-changed
    #     - type: section
    #       label: Bathroom
    #     - entity: light.shelly_shsw_1_ba6933
    #       secondary_info: last-changed  
  
  
  
  
#   cards:
#     - type: vertical-stack
#       cards:
#         - type: glance
#           entities:
#             - entity: sensor.tesla_battery_level
#               name: Battery Level
#             - entity: sensor.tesla_state
#               name: Car State
#             - entity: sensor.tesla_plugged_in
#               name: Plugged In
#         - type: glance
#           entities:
#             - entity: sensor.tesla_park_brake
#               name: Park Brake
#             - entity: sensor.tesla_sentry_mode
#               name: Sentry Mode
#             - entity: sensor.tesla_speed
#               name: Speed
#         - type: glance
#           entities:
#             - entity: sensor.tesla_healthy
#               name: Car Health
#             - entity: sensor.tesla_windows_open
#               name: Window Status
#         - type: horizontal-stack
#           cards:
#             - type: "custom:button-card"
#               entity: sensor.tesla_locked
#               name: Charger Door
#               show_state: true
#               state:
#                 - value: locked
#                   icon: "mdi:lock"
#                   color: green
#                   tap_action:
#                     action: call-service
#                     service: lock.unlock
#                     service_data:
#                       entity_id: lock.tesla_model_3_charger_door_lock
#                 - value: unlocked
#                   icon: "mdi:lock-open"
#                   color: red
#                   tap_action:
#                     action: call-service
#                     service: lock.lock
#                     service_data:
#                       entity_id: lock.tesla_model_3_charger_door_lock
#             - type: "custom:button-card"
#               entity: lock.tesla_door_lock
#               name: Car Door
#               show_state: true
#               state:
#                 - value: locked
#                   icon: "mdi:lock"
#                   color: green
#                   tap_action:
#                     action: call-service
#                     service: lock.unlock
#                     service_data:
#                       entity_id: lock.tesla_model_3_door_lock
#                 - value: unlocked
#                   icon: "mdi:lock-open"
#                   color: red
#                   tap_action:
#                     action: call-service
#                     service: lock.lock
#                     service_data:
#                       entity_id: lock.tesla_model_3_door_lock
#     - type: vertical-stack
#       cards:
#         - type: map
#           entities:
#             - device_tracker.tesla_location
#         - type: thermostat
#           entity: climate.tesla_model_3_hvac_climate_system
#     - type: entities
#       entities:
#         - entity: sensor.tesla_charge_limit
#           name: SOC Charge Limit
#         - entity: sensor.tesla_charge_energy_added
#           name: Last Charge Energy Added
#         - entity: sensor.tesla_odometer
#           name: Odometer
#         - entity: sensor.tesla_estimated_range
#           name: Estimated Range
#         - entity: sensor.tesla_rated_range
#           name: Rated Range
#         - entity: sensor.tesla_inside_temp
#           name: Tesla Temperature (inside)
#         - entity: sensor.tesla_outside_temp
#           name: Tesla Temperature (outside)
#         - entity: proximity.home_tesla
#           name: Distance to Home
