camera:
  # - platform: generic
  #   name: kitchen_tablet
  #   still_image_url: !secret fully_kiosk_cam_still

  - platform: generic
    name: Drive
    still_image_url: !secret Drive_Camera_Still
    stream_source: !secret Drive_Camera_Source

  - platform: generic
    name: Drive_sub
    still_image_url: !secret Drive_Camera_Still
    stream_source: !secret Drive_sub_Camera_Source

  - platform: generic
    name: Porch
    still_image_url: !secret Porch_Camera_Still
    stream_source: !secret Porch_Camera_Source

  - platform: generic
    name: Garden
    still_image_url: !secret Garden_Camera_Still
    stream_source: !secret Garden_Camera_Source

  - platform: generic
    name: Nursery
    still_image_url: !secret Nursery_Camera_Still
    stream_source: !secret Nursery_Camera_Source

#   - platform: generic
#     name: Drive_SYNO
#     still_image_url: !secret Drive_SYNO_Camera_Still
#     stream_source: !secret Drive_SYNO_Camera_Source

#   - platform: generic
#     name: Porch_SYNO
#     still_image_url: !secret Porch_SYNO_Camera_Still
#     stream_source: !secret Porch_SYNO_Camera_Source

#   - platform: generic
#     name: Garden_SYNO
#     still_image_url: !secret Garden_SYNO_Camera_Still
#     stream_source: !secret Garden_SYNO_Camera_Source

#Enable stream
stream:
