image_processing:
  - platform: deepstack_object
    ip_address: deepstack
    port: 5000
    api_key: !secret deepstackkey
    save_file_folder: /config/camera_snapshots/drive
    save_timestamped_file: True
    timeout: 30
    # scan_interval: 30
    confidence: 40
    # roi_x_min: 0
    # roi_x_max: 1
    # roi_y_min: 0
    # roi_y_max: 1
    targets:
      - person
      - car
    source:
      - entity_id: camera.prettyflynas_drive_camera
        name: drive_image_recognition
  - platform: deepstack_object
    ip_address: deepstack
    port: 5000
    api_key: !secret deepstackkey
    save_file_folder: /config/camera_snapshots/porch
    save_timestamped_file: True
    timeout: 30
    # scan_interval: 30
    confidence: 40
    # roi_x_min: 0
    # roi_x_max: 1
    # roi_y_min: 0
    # roi_y_max: 1
    targets:
      - person
    source:
      - entity_id: camera.prettyflynas_porch_camera
        name: porch_image_recognition
  - platform: deepstack_object
    ip_address: deepstack
    port: 5000
    api_key: !secret deepstackkey
    save_file_folder: /config/camera_snapshots/garden
    save_timestamped_file: True
    timeout: 30
    # scan_interval: 30
    confidence: 40
    # roi_x_min: 0
    # roi_x_max: 1
    # roi_y_min: 0
    # roi_y_max: 1
    targets:
      - person
    source:
      - entity_id: camera.prettyflynas_back_garden_camera
        name: garden_image_recognition
camera:
  - platform: local_file
    file_path: /config/camera_snapshots/drive/drive_image_recognition_latest.jpg
    name: drive_latest
  - platform: local_file
    file_path: /config/camera_snapshots/porch/porch_image_recognition_latest.jpg
    name: porch_latest    
  - platform: local_file
    file_path: /config/camera_snapshots/garden/garden_image_recognition_latest.jpg
    name: garden_latest
