image_processing:
  - platform: deepstack_object
    ip_address: deepstack
    # name: drive_image_recogntion
    port: 5000
    api_key: !secret deepstackkey
    save_file_folder: /config/camera_snapshots/
    save_timestamped_file: True
    timeout: 30
    scan_interval: 30
    confidence: 40
    # roi_x_min: 0
    # roi_x_max: 1
    # roi_y_min: 0
    # roi_y_max: 1
    targets:
      - person
      - car
    source:
      - entity_id: camera.Drive_sub
        name: drive_image_recognition

camera:
  - platform: local_file
    file_path: /config/camera_snapshots/drive_image_recognition_latest.jpg
    name: deepstack_latest_person

