input_boolean:
  toggle_motion_fill:
      name: Toggle Motion Fill
      initial: off
      icon: mdi:toggle-switch
#   toggle_battery_warning:
#       name: Toggle Battery Warning
#       initial: off
#       icon: mdi:toggle-switch
#   toggle_motion_border:
#       name: Toggle Motion Border
#       initial: on
#       icon: mdi:toggle-switch


binary_sensor:
  - platform: template
    sensors:

# ###### DOWNSTAIRS - Motion Fill Shapes ######
<<<<<<< HEAD
#       living_room_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
#       library_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
#       kitchen_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('binary_sensor.day_room_motion_1', 'on') }}"
      hallway_motion_fill:
        device_class: motion
        value_template: "{{ is_state('binary_sensor.z2_motion_hall_ias_zone', 'on') }}"
#       front_door_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
#       downstairs_bathroom_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
#       outdoor_side_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
#       outdoor_front_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
#       outdoor_back_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
#
#
=======
      living_room_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      library_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      kitchen_motion_fill:
        device_class: motion
        value_template: "{{ is_state('binary_sensor.day_room_motion_1', 'on') }}"
      hallway_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      front_door_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      downstairs_bathroom_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      outdoor_side_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      outdoor_front_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      outdoor_back_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"


>>>>>>> 52201e39f5faccb4e28ff6c5aaa5d4acd6f664e7
# ###### DOWNSTAIRS - Motion Stroke Shapes ######
#       living_room_motion_border:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_border', 'on') }}"
#       library_motion_border:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_border', 'on') }}"
#       kitchen_motion_border:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_border', 'on') }}"
#       hallway_motion_border:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_border', 'on') }}"
#       front_door_motion_border:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_border', 'on') }}"
#       downstairs_bathroom_motion_border:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_border', 'on') }}"

###### DOWNSTAIRS - Battery Warning Shapes ######
      kitchen_temp_battery:
        device_class: battery
        value_template: "{{ states('sensor.kitchen_battery_level')| float < 10}}"
      day_room_temp_battery:
        device_class: battery
        value_template: "{{ states('sensor.day_room_battery_level')| float < 10}}"
      day_room_motion_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      living_room_window_4_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      living_room_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      living_room_window_2_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      hallway_door_1_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      library_door_1_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      kitchen_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      kitchen_window_2_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      downstairs_bathroom_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      kitchen_door_1_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      living_room_window_3_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"

# ###### UPSTAIRS - Motion Fill Shapes ######
      landing_motion_fill:
        device_class: motion
<<<<<<< HEAD
        value_template: "{{ is_state('binary_sensor.z1_motion_landing_ias_zone', 'on') }}"
#       bedroom_3_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
#       bedroom_1_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
#       bathroom_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
#       bedroom_2_motion_fill:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
=======
        value_template: "{{ is_state('binary_sensor.landing_motion', 'on') }}"
      bedroom_3_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      bedroom_1_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      bathroom_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      bedroom_2_motion_fill:
        device_class: motion
        value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
>>>>>>> 52201e39f5faccb4e28ff6c5aaa5d4acd6f664e7

# ###### UPSTAIRS - Motion Stroke Shapes ######
#
#       landing_motion_border:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_border', 'on') }}"
#       bedroom_3_motion_border:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_border', 'on') }}"
#       bedroom_1_motion_border:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_border', 'on') }}"
#       bathroom_motion_border:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_border', 'on') }}"
#       bedroom_2_motion_border:
#         device_class: motion
#         value_template: "{{ is_state('input_boolean.toggle_motion_border', 'on') }}"

###### UPSTAIRS - Battery Warning Shapes ######

      bedroom_1_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      bedroom_1_window_4_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      bedroom_1_window_2_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      bedroom_1_window_3_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      bedroom_2_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      bathroom_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      bedroom_3_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"
      bedroom_1_window_5_battery:
        device_class: battery
        value_template: "{{ is_state('input_boolean.toggle_battery_warning', 'on') }}"

###### DOWNSTAIRS - Opening ######

      living_room_window_2:
          device_class: door
          value_template: "{{ is_state('binary_sensor.test_room_opening', 'on') }}"
      living_room_window_3:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      living_room_window_1:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      living_room_window_4:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      library_door_1:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      kitchen_window_1:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      kitchen_window_2:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      # downstairs_bathroom_window_1:
      #     device_class: door
      #     value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      kitchen_door_1:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      hallway_door_1:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"

sensor:
  - platform: template
    sensors:

###### DOWNSTAIRS - Thermometer Shapes ######
      # living_room_motion_fill:
      #   device_class: motion
      #   value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
       # "{{ states('sensor.day_room_temperature') }}"
      day_room_therm:
        device_class: temperature
        value_template:  >
            {% if is_state('sensor.day_room_temperature', 'unavailable') %}
              ?
            {% else %}
              states('sensor.day_room_temperature')
            {% endif %}


      kitchen_therm:
        device_class: temperature
        value_template: "{{ states('sensor.kitchen_temperature') }}"
      # hallway_motion_fill:
      #   device_class: motion
      #   value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      # front_door_motion_fill:
      #   device_class: motion
      #   value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      # downstairs_bathroom_motion_fill:
      #   device_class: motion
      #   value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      # outdoor_side_motion_fill:
      #   device_class: motion
      #   value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      # outdoor_front_motion_fill:
      #   device_class: motion
      #   value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
      # outdoor_back_motion_fill:
      #   device_class: motion
      #   value_template: "{{ is_state('input_boolean.toggle_motion_fill', 'on') }}"
