binary_sensor:
  - platform: template
    sensors:

###### DOWNSTAIRS - Motion Fill Shapes ######
      living_room_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      library_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      kitchen_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      hallway_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      front_door_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      downstairs_bathroom_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      outdoor_side_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      outdoor_front_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      outdoor_back_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"

###### DOWNSTAIRS - Motion Stroke Shapes ######
      living_room_motion_border:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      library_motion_border:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      kitchen_motion_border:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      hallway_motion_border:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      front_door_motion_border:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      downstairs_bathroom_motion_border:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"

###### DOWNSTAIRS - Battery Warning Shapes ######
      living_room_window_4_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      living_room_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      living_room_window_2_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      hallway_door_1_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      library_door_1_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      kitchen_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      kitchen_window_2_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      downstairs_bathroom_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      kitchen_door_1_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      living_room_window_3_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"

###### UPSTAIRS - Motion Fill Shapes ######
      landing_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_3_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_1_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bathroom_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_2_motion_fill:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"

###### UPSTAIRS - Motion Stroke Shapes ######

      landing_motion_border:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_3_motion_border:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_1_motion_border:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bathroom_motion_border:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_2_motion_border:
        device_class: motion
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"

###### UPSTAIRS - Battery Warning Shapes ######

      bedroom_1_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_1_window_4_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_1_window_2_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_1_window_3_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_2_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bathroom_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_3_window_1_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"
      bedroom_1_window_5_battery:
        device_class: battery
        value_template: "{{ is_state('switch.test_room_light', 'on') }}"

###### DOWNSTAIRS - Opening ######

      living_room_window_2:
          device_class: door
          value_template: "{{ is_state('binary_sensor.test_room_opening', 'on') }}"
      living_room_window_3:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      living_room_window_1:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      living_room_window_4:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      library_door_1:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      kitchen_window_1:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      kitchen_window_2:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      # downstairs_bathroom_window_1:
      #     device_class: door
      #     value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      kitchen_door_1:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"
      hallway_door_1:
          device_class: door
          value_template: "{{ states.binary_sensor.test_room_opening.state }}"

# ##### Temperature template

sensor:
  - platform: template
    sensor:
      living_room_temp_text:
          value_template: "{{ states.sensor.test_room_temp.state }} \n {{ states.sensor.test_room_humidity.state }}"
