climate:
  - platform: mqtt
    name: Kitchen Floor
    mode_command_topic: "TEST/heating/ufh/mode_command"
    mode_state_topic: "TEST/heating/ufh/mode_state"
    temperature_state_topic: "TEST/heating/ufh/currentsetpoint"
    temperature_command_topic: "TEST/heating/ufh/currentsetpoint/command"
    current_temperature_topic: "TEST/heating/ufh/temperature"
    value_template: "{{ value_json }}"
    initial: 20
    qos: 0
    payload_on: ON
    payload_off: OFF
    modes:
      - "auto"
      - "heat"
      - "off"
    min_temp: 12
    max_temp: 30
    temp_step: 1
    retain: true

    # mode_command_topic: "TEST/cmnd/heating/ufh/sonoff"
    # mode_state_topic: "TEST/tele/heating/ufh/sonoff/STATE"
    # mode_state_template: "{{ value_json.POWER.value }}"


#IF FLOOR IS AT TEMP, ROOM IS AT TEMP - Turn both off
#IF FLOOR IS AT TEMP, ROOM IS NOT AT TEMP - Turn both on
#IF FLOOR IS NOT AT TEMP, ROOM IS AT TEMP - Turn rad off
