# INFLUXDB
influxdb:
  host: influxdb
  port: 8086
  database: homeassistant
  username: !secret hass_username
  password: !secret hass_password
  default_measurement: state
  tags_attributes:
    - friendly_name
  include:
    entities:
      #WISER HEATING
      - sensor.wiser_heating
      - climate.wiser_master
      - climate.wiser_bedroom_3
      - climate.wiser_bedroom_2
      - climate.wiser_living_room
      - climate.wiser_kitchen
      - sensor.main_heating_status
      - sensor.kitchen_heating_status
      - sensor.living_room_heating_status
      - sensor.master_heating_status
      - sensor.bed_3_heating_status
      - sensor.bed_2_heating_status

      #WEATHER
      - weather.dark_sky
      #LIGHTS
      - light.shelly_shsw_1_ba680b
      - light.shelly_shsw_1_c4ef56
      - light.shelly_shsw_1_c487ec
      - light.shelly_shdm_1_f3e93b
      - sensor.shelly_shdm_1_f3e93b_current_consumption
      - sensor.shelly_shdm_1_f3e93b_total_consumption
      - light.shelly_shsw_1_c4e83e
      - light.shelly_shdm_1_f3ebd2
      - sensor.shelly_shdm_1_f3ebd2_current_consumption
      - sensor.shelly_shdm_1_f3ebd2_total_consumption
      - light.shelly_shdm_1_f3a24c
      - sensor.shelly_shdm_1_f3a24c_current_consumption
      - sensor.shelly_shdm_1_f3a24c_total_consumption
      - light.shelly_shdm_1_db3e10
      - sensor.shelly_shdm_1_db3e10_current_consumption
      - switch.shelly_shsw_1_a4cf12f41faf #table
      - light.shelly_shsw_1_a4cf12f42d0b #marks bedside light
      - switch.shelly_shsw_1_a4cf12f46b5a  #tall lamp
      - switch.sonoff_basic_on_off #nursery night light

      #TESLA
      - sensor.tez_mileage_sensor
      - sensor.tez_battery_sensor
      - sensor.tez_range_sensor
      - switch.tez_charger_switch

      #Energy
      - sensor.shelly_shem_b9ebe7_1_current_consumption
      - sensor.shelly_shem_b9ebe7_1_total_consumption
      - sensor.shelly_shem_b9ebe7_2_current_consumption
      - sensor.shelly_shem_b9ebe7_2_total_consumption
      - sensor.elec_1_hour
      - sensor.elec_1_day
      - sensor.elec_1_week
      - sensor.elec_1_month
      - sensor.elec_2_hour
      - sensor.elec_2_day
      - sensor.elec_2_week
      - sensor.elec_2_month
      - sensor.shelly_shsw_pm_f2760d_current_consumption
      - sensor.shelly_shsw_pm_f2760d_total_consumption
      #dishswasher
      - switch.shelly_shsw_pm_f2760d 
      - sensor.shelly_shsw_pm_f2760d_total_consumption
      - sensor.shelly_shsw_pm_f2760d_current_consumption
      #washing machine
      - switch.shelly_shsw_pm_f27e6f
      - sensor.shelly_shsw_pm_f27e6f_current_consumption
      - sensor.shelly_shsw_pm_f27e6f_total_consumption
      #tumble dryer
      - switch.shelly_shsw_pm_f2febe
      - sensor.shelly_shsw_pm_f2febe_total_consumption
      - sensor.shelly_shsw_pm_f2febe_current_consumption
      
      #TEMPERATURE
      - sensor.xiaomi_1_temperature
      - sensor.xiaomi_2_temperature
      - sensor.z1_temp_outdoor
      - sensor.z2_temp_temperature
      - sensor.z3_temp_temperature
      - sensor.z1_humidity_outdoor
      - sensor.z2_temp_humidity
      - sensor.z3_temp_humidity
       


      
    domains:
      - lights
      - climate
      - utility_meter
      
sensor:
  - platform: template
    sensors:
      main_heating_status:
        friendly_name: "Main Heating Status"
        value_template: >-
          {% if is_state('sensor.wiser_heating', 'Off') %}
            0
          {% elif is_state('sensor.wiser_heating', 'On') %}
            1
          {% else %}
            Error
          {% endif %}
      kitchen_heating_status:
        friendly_name: "Kitchen Heating Status"
        value_template: >-
          {% if is_state_attr('climate.wiser_kitchen', 'control_output_state', 'Off') %}
            0
          {% elif is_state_attr('climate.wiser_kitchen', 'control_output_state', 'On') %}
            1
          {% else %}
            Error
          {% endif %}
      living_room_heating_status:
        friendly_name: "Living Room Heating Status"
        value_template: >-
          {% if is_state_attr('climate.wiser_living_room', 'control_output_state', 'Off') %}
            0
          {% elif is_state_attr('climate.wiser_living_room', 'control_output_state', 'On') %}
            1
          {% else %}
            Error
          {% endif %}
      master_heating_status:
        friendly_name: "Master Heating Status"
        value_template: >-
          {% if is_state_attr('climate.wiser_master', 'control_output_state', 'Off') %}
            0
          {% elif is_state_attr('climate.wiser_master', 'control_output_state', 'On') %}
            1
          {% else %}
            Error
          {% endif %}
      bed_2_heating_status:
        friendly_name: "Bedroom 2 Heating Status"
        value_template: >-
          {% if is_state_attr('climate.wiser_bedroom_2', 'control_output_state', 'Off') %}
            0
          {% elif is_state_attr('climate.wiser_bedroom_2', 'control_output_state', 'On') %}
            1
          {% else %}
            Error
          {% endif %}
      bed_3_heating_status:
        friendly_name: "Bedroom 3 Heating Status"
        value_template: >-
          {% if is_state_attr('climate.wiser_bedroom_3', 'control_output_state', 'Off') %}
            0
          {% elif is_state_attr('climate.wiser_bedroom_3', 'control_output_state', 'On') %}
            1
          {% else %}
            Error
          {% endif %}
