# sensor:
#   - platform: template
#     sensors:
#       ha_versions:
#         friendly_name: Node Red
#         value_template: "{{ states.sensor.current_ha_version.state }}  /  {{ states.sensor.latest_ha_version.state }}"
#
#   #Home Assistant Version (current)
#   - platform: file
#     name: "Current Node Red Version"
#     file_path: "/config/version_files/node-red/.config.json"
#     value_template: "{{ value_json.homeassistant.default }}"
#
#     # icon: mdi:home
#
#   #Home Assistant Version (available)
#   - platform: rest
#     resource: https://s3.amazonaws.com/hassio-version/stable.json
#     name: "Latest HA Version"
#     value_template: "{{ value_json.homeassistant.default }}"
#     scan_interval: 36000
#     # icon: mdi:home
#
# sensor.current_ha_version:
#   # <<: *customize
#   friendly_name: "Current HA Version"
# sensor.latest_ha_version:
#   # <<: *customize
#   friendly_name: "Latest HA Version"
