light:
  - platform: mqtt
    name: "Kitchen Cupboard Light"
    state_topic: "stat/sonoff-cupboard-light/RESULT"
    value_template: "{{ value_json.POWER }}"
    command_topic: "cmnd/sonoff-cupboard-light/power"
    availability_topic: "tele/sonoff-cupboard-light/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: false