switch:
  - platform: mqtt
    name: "test_room_light"
    state_topic: "test.home/test_room/lights/state"
    command_topic: "test.home/test_room/lights/set"
    availability_topic: "test.home/test_room/lights/available"
    payload_on: "ON"
    payload_off: "OFF"
    state_on: "ON"
    state_off: "OFF"
    optimistic: false
    qos: 0
    retain: true
    unique_id: 001234534214235

binary_sensor:
  - platform: mqtt
    name: "test_room_opening"
    state_topic: "test.home/test_room/opening_1/state"
    availability_topic: "test.home/test_room/opening_1/available"
    payload_on: "ON"
    payload_off: "OFF"
    # optimistic: false
    qos: 0
    # retain: true
    unique_id: 001121312445534

binary_sensor.test_room_opening:
  # <<: *customize
  device_class: door

sensor:
  - platform: mqtt
    state_topic: "TEST/downstairs_bathroom/temperature"
    name: "downstairs_bathroom_temp"
    unit_of_measurement: "ºC"
    value_template: "{{  value | round(1) }}"

sensor:
  - platform: mqtt
    state_topic: "TEST/downstairs_bathroom/humidity"
    name: "downstairs_bathroom_humidity"
    unit_of_measurement: "%"
    value_template: "{{  value | round(1) }}"

binary_sensor:
  - platform: mqtt
    name: "downstairs_bathroom_window_1"
    state_topic: "test.home/test_room/opening_1/state"
    availability_topic: "test.home/test_room/opening_1/available"
    payload_on: "ON"
    payload_off: "OFF"
    # optimistic: false
    qos: 0
    # retain: true
    unique_id: 001121312445534
