sensor:
  - platform: uk_transport
    app_id: !secret transport_APP_ID
    app_key: !secret transport_APP_KEY
    scan_interval: 100000
    queries:
      - mode: train
        origin: WAL
        destination: WAT
      # - mode: train
      #   origin: WAT
      #   destination: WAL


input_boolean:
  toggle_transport_api:
    name: Toggle Transport api
    initial: on
    icon: mdi:train
