utility_meter:
  elec_1_month:
    source: sensor.shelly_shem_b9ebe7_1_total_consumption
    cycle: monthly
  elec_1_week:
    source: sensor.shelly_shem_b9ebe7_1_total_consumption
    cycle: weekly
  elec_1_day:
    source: sensor.shelly_shem_b9ebe7_1_total_consumption
    cycle: daily
  elec_1_hour:
    source: sensor.shelly_shem_b9ebe7_1_total_consumption
    cycle: hourly
  elec_2_month:
    source: sensor.shelly_shem_b9ebe7_2_total_consumption
    cycle: monthly
  elec_2_week:
    source: sensor.shelly_shem_b9ebe7_2_total_consumption
    cycle: weekly
  elec_2_day:
    source: sensor.shelly_shem_b9ebe7_2_total_consumption
    cycle: daily
  elec_2_hour:
    source: sensor.shelly_shem_b9ebe7_2_total_consumption
    cycle: hourly
