- type: "custom:button-card"
  entity: person.mark_colling
  icon: mdi:shoe-print
  color: var(--primary-text-color)
  color_type: icon
  default_color: var(--disabled-text-color)
  tap_action:
    action: more-info
  name: Mark
  state:
    - value: 'home'
      icon: mdi:home-account
      color: var(--primary-color)
  # style: |
  #   ha-card {
  #     background:
  #     {% if is_state('person.mark_colling', 'home') %}
  #       var(--primary-color)
  #     {% else %}
  #       var(--disabled-text-color)
  #     {% endif %};
  #   }
  styles:
    card:
    - height: 98px
    # - font-size: 12px
    # - font-weight: bold
- type: "custom:button-card"
  entity: person.katie
  icon: mdi:shoe-print
  color: var(--primary-text-color)
  color_type: icon
  default_color: var(--disabled-text-color)
  tap_action:
    action: more-info
  state:
    - value: 'home'
      icon: mdi:home-account
      color: var(--primary-color)
  name: Katie
  styles:
    card:
    - height: 98px
    # - font-size: 12px
    # - font-weight: bold
- type: "custom:button-card"
  entity: input_boolean.bins_put_out
  show_name: false
  show_entity_picture: true
  entity_picture: >
    [[[
      if (states['sensor.recycling_bin_next'].state == "True")
        return "/local/icons/bins/recycle_bin.svg";
      else
        return "/local/icons/bins/green_garden_waste.svg";
    ]]]
  # color: var(--primary-color)
  # color_type: icon
  # default_color: var(--primary-color)
  styles:
    card:
    - height: 98px
    - background-color: >
        [[[
          if (states['input_boolean.bins_put_out'].state == "off" && states['sensor.bins_should_be_out'].state == "True")
            return "#de3429";
          else if (states['input_boolean.bins_put_out'].state == "on" && states['sensor.bins_should_be_out'].state == "False")
            return "#ff9800";
          return "#00000000";
        ]]]
    - animation: >
        [[[
          if (states['input_boolean.bins_put_out'].state == "off" && states['sensor.bins_should_be_out'].state == "True")
            return "blink 2s ease infinite";
          return "#00000000";
        ]]]
    entity_picture:
      - height: >
          [[[
            if (states['sensor.recycling_bin_next'].state == "True")
              return '80%';
            else
              return '60%';
          ]]]
      - width: 100%
  # name: Bins
  tap_action:
    action: toggle
    entity: input_boolean.bins_put_out
    confirmation:
      text: >
        [[[
          if (entity.state == "off")
            return "Have you put the bins out?";
          else
            return "Have you brought the bins in?";
        ]]]
