- type: "custom:button-card"
  entity: person.mark_colling
  icon: mdi:shoe-print
  color: var(--primary-text-color)
  color_type: icon
  default_color: var(--disabled-text-color)
  tap_action:
    action: more-info
  name: Mark
  state:
    - value: 'home'
      icon: mdi:home-account
      color: var(--primary-color)
  # style: |
  #   ha-card {
  #     background:
  #     {% if is_state('person.mark_colling', 'home') %}
  #       var(--primary-color)
  #     {% else %}
  #       var(--disabled-text-color)
  #     {% endif %};
  #   }
  styles:
    card:
    - height: 98px
    # - font-size: 12px
    # - font-weight: bold
- type: "custom:button-card"
  entity: person.katie
  icon: mdi:shoe-print
  color: var(--primary-text-color)
  color_type: icon
  default_color: var(--disabled-text-color)
  tap_action:
    action: more-info
  state:
    - value: 'home'
      icon: mdi:home-account
      color: var(--primary-color)
  name: Katie
  styles:
    card:
    - height: 98px
    # - font-size: 12px
    # - font-weight: bold
- type: "custom:button-card"
  entity: light.xmas_lights
  # icon: mdi:lightbulb
  color: auto
  color_type: icon
  icon: mdi:pine-tree
  default_color: rgb(255, 233, 155)
  action: toggle
  name: Xmas Lights
  styles:
    card:
    - height: 98px
  # state:
  #   - value: default
  #     colour: var(--disabled-text-color)
  #     styles:
  #       label:
  #         - colour: var(--disabled-text-color)
    # - font-size: 12px
    # - font-weight: bold
- type: "custom:button-card"
  entity: switch.xmas_lights_mode
  # icon: mdi:lightbulb
  color: auto
  color_type: icon
  icon: mdi:pine-tree
  default_color: rgb(255, 233, 155)
  action: toggle
  name: Xmas Lights Mode
  styles:
    card:
    - height: 98px
