esphome:
  name: temp_sensor_hub
  platform: ESP32
  board: esp32dev

wifi:
  ssid: !env_var WIFI_SSID
  password: !env_var WIFI_PWD
  
  use_address: 192.168.1.34
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Temp Sensor Hub Fallback Hotspot"
    password: "52bqLsukXFBJ"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

# Enable Bluetooth scanning for this ESP32
esp32_ble_tracker:

sensor:
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:36:B0:9A
    temperature:
      name: "Xiaomi 1 Temperature"
    humidity:
      name: "Xiaomi 1 Humidity"
    battery_level:
      name: "Xiaomi 1 Battery Level"
  - platform: xiaomi_lywsdcgq
    mac_address: 58:2D:34:36:B2:89
    temperature:
      name: "Xiaomi 2 Temperature"
    humidity:
      name: "Xiaomi 2 Humidity"
    battery_level:
      name: "Xiaomi 2 Battery Level"

# time:
#   - platform: homeassistant
#     on_time:
#       - seconds: 0
#         minutes: 0
#         hours: 4
#         days_of_week: MON-SUN
#         then:
#           - switch.toggle: restart_switch

switch:
  - platform: restart
    name: "test_temperature Restart"
    id: restart_switch

